import type { ApiKey, WebhookEvent, Workflow } from "@/lib/types";

/**
 * Datos de demostración. Sustitúyelos por consultas a Supabase cuando la base
 * de datos esté poblada (hay un ejemplo comentado en cada página).
 */

const minutesAgo = (minutes: number): string =>
  new Date(Date.now() - minutes * 60_000).toISOString();

export const MOCK_WORKFLOWS: readonly Workflow[] = [
  {
    id: "wf_3kd9alpha",
    name: "Cobro fallido a Slack",
    description: "Avisa al canal #finanzas cuando Stripe rechaza un pago recurrente.",
    status: "active",
    trigger: "webhook",
    steps: [
      { id: "s1", label: "Pago rechazado", kind: "trigger", service: "Stripe" },
      { id: "s2", label: "Importe mayor a 50 €", kind: "filter", service: "Filtro" },
      { id: "s3", label: "Publicar en #finanzas", kind: "action", service: "Slack" },
    ],
    runsToday: 128,
    runsTotal: 14_902,
    successRate: 99.2,
    avgDurationMs: 412,
    lastRunAt: minutesAgo(3),
    createdAt: "2026-02-11T10:00:00.000Z",
  },
  {
    id: "wf_7mq2beta",
    name: "Alta de cliente a CRM",
    description: "Crea el contacto en HubSpot y le envía el correo de bienvenida.",
    status: "active",
    trigger: "webhook",
    steps: [
      { id: "s1", label: "Formulario enviado", kind: "trigger", service: "Typeform" },
      { id: "s2", label: "Crear contacto", kind: "action", service: "HubSpot" },
      { id: "s3", label: "Enviar bienvenida", kind: "action", service: "Resend" },
    ],
    runsToday: 41,
    runsTotal: 3_118,
    successRate: 97.6,
    avgDurationMs: 1_240,
    lastRunAt: minutesAgo(17),
    createdAt: "2026-03-02T09:30:00.000Z",
  },
  {
    id: "wf_1xz8gamma",
    name: "Resumen diario de ventas",
    description: "Agrega los pedidos del día y los envía por correo a las 20:00.",
    status: "active",
    trigger: "schedule",
    steps: [
      { id: "s1", label: "Cada día a las 20:00", kind: "trigger", service: "Programado" },
      { id: "s2", label: "Leer pedidos", kind: "action", service: "Supabase" },
      { id: "s3", label: "Enviar resumen", kind: "action", service: "Resend" },
    ],
    runsToday: 1,
    runsTotal: 214,
    successRate: 100,
    avgDurationMs: 3_980,
    lastRunAt: minutesAgo(640),
    createdAt: "2025-11-19T18:05:00.000Z",
  },
  {
    id: "wf_5jp4delta",
    name: "Sincronizar inventario",
    description: "Iguala el stock de Shopify con el almacén cada hora.",
    status: "paused",
    trigger: "schedule",
    steps: [
      { id: "s1", label: "Cada hora", kind: "trigger", service: "Programado" },
      { id: "s2", label: "Sólo productos activos", kind: "filter", service: "Filtro" },
      { id: "s3", label: "Actualizar stock", kind: "action", service: "Shopify" },
    ],
    runsToday: 0,
    runsTotal: 8_760,
    successRate: 94.1,
    avgDurationMs: 2_150,
    lastRunAt: minutesAgo(2_880),
    createdAt: "2025-09-08T12:00:00.000Z",
  },
  {
    id: "wf_9bt6epsilon",
    name: "Incidencias a Linear",
    description: "Convierte cada error reportado por Sentry en una incidencia priorizada.",
    status: "active",
    trigger: "webhook",
    steps: [
      { id: "s1", label: "Error nuevo", kind: "trigger", service: "Sentry" },
      { id: "s2", label: "Entorno de producción", kind: "filter", service: "Filtro" },
      { id: "s3", label: "Crear incidencia", kind: "action", service: "Linear" },
    ],
    runsToday: 9,
    runsTotal: 671,
    successRate: 88.4,
    avgDurationMs: 760,
    lastRunAt: minutesAgo(52),
    createdAt: "2026-01-23T08:45:00.000Z",
  },
  {
    id: "wf_2vn0zeta",
    name: "Recordatorio de renovación",
    description: "Escribe al cliente siete días antes de que caduque su suscripción.",
    status: "draft",
    trigger: "schedule",
    steps: [
      { id: "s1", label: "Cada día a las 09:00", kind: "trigger", service: "Programado" },
      { id: "s2", label: "Caduca en 7 días", kind: "filter", service: "Filtro" },
      { id: "s3", label: "Enviar recordatorio", kind: "action", service: "Resend" },
    ],
    runsToday: 0,
    runsTotal: 0,
    successRate: 0,
    avgDurationMs: 0,
    lastRunAt: null,
    createdAt: "2026-09-01T16:20:00.000Z",
  },
];

export const MOCK_EVENTS: readonly WebhookEvent[] = [
  {
    id: "evt_9f2c41a7b0",
    workflowId: "wf_3kd9alpha",
    workflowName: "Cobro fallido a Slack",
    endpoint: "/hooks/stripe/payment-failed",
    method: "POST",
    status: "success",
    statusCode: 200,
    durationMs: 388,
    attempts: 1,
    receivedAt: minutesAgo(2),
    payload: {
      type: "invoice.payment_failed",
      customer: "cus_QX82mfa",
      amount: 7900,
      currency: "eur",
    },
    errorMessage: null,
  },
  {
    id: "evt_7ab3c9d112",
    workflowId: "wf_9bt6epsilon",
    workflowName: "Incidencias a Linear",
    endpoint: "/hooks/sentry/issue-created",
    method: "POST",
    status: "failed",
    statusCode: 502,
    durationMs: 9_840,
    attempts: 3,
    receivedAt: minutesAgo(6),
    payload: {
      level: "error",
      project: "checkout-api",
      culprit: "POST /v1/orders",
      environment: "production",
    },
    errorMessage: "Linear respondió 502 tras 3 intentos. El siguiente reintento es en 15 minutos.",
  },
  {
    id: "evt_4cc8e01f5a",
    workflowId: "wf_7mq2beta",
    workflowName: "Alta de cliente a CRM",
    endpoint: "/hooks/typeform/submission",
    method: "POST",
    status: "pending",
    statusCode: null,
    durationMs: 0,
    attempts: 1,
    receivedAt: minutesAgo(8),
    payload: {
      form_id: "Gv4kL2",
      email: "marta.ruiz@empresa.com",
      plan: "pro",
    },
    errorMessage: null,
  },
  {
    id: "evt_1de6b74c39",
    workflowId: "wf_3kd9alpha",
    workflowName: "Cobro fallido a Slack",
    endpoint: "/hooks/stripe/payment-failed",
    method: "POST",
    status: "success",
    statusCode: 200,
    durationMs: 402,
    attempts: 1,
    receivedAt: minutesAgo(21),
    payload: {
      type: "invoice.payment_failed",
      customer: "cus_PL10zzq",
      amount: 2400,
      currency: "eur",
    },
    errorMessage: null,
  },
  {
    id: "evt_8fa2079e64",
    workflowId: "wf_7mq2beta",
    workflowName: "Alta de cliente a CRM",
    endpoint: "/hooks/typeform/submission",
    method: "POST",
    status: "failed",
    statusCode: 422,
    durationMs: 1_105,
    attempts: 2,
    receivedAt: minutesAgo(38),
    payload: {
      form_id: "Gv4kL2",
      email: "correo-no-valido",
      plan: "starter",
    },
    errorMessage: "HubSpot rechazó el contacto: el campo email no tiene un formato válido.",
  },
  {
    id: "evt_6bd5138a02",
    workflowId: "wf_1xz8gamma",
    workflowName: "Resumen diario de ventas",
    endpoint: "/hooks/internal/daily-digest",
    method: "POST",
    status: "success",
    statusCode: 200,
    durationMs: 3_912,
    attempts: 1,
    receivedAt: minutesAgo(94),
    payload: { orders: 187, revenue: 12_480.5, currency: "eur" },
    errorMessage: null,
  },
  {
    id: "evt_3ef90c6d77",
    workflowId: "wf_9bt6epsilon",
    workflowName: "Incidencias a Linear",
    endpoint: "/hooks/sentry/issue-created",
    method: "POST",
    status: "success",
    statusCode: 201,
    durationMs: 742,
    attempts: 1,
    receivedAt: minutesAgo(150),
    payload: { level: "warning", project: "web", environment: "production" },
    errorMessage: null,
  },
  {
    id: "evt_0aa74be215",
    workflowId: "wf_5jp4delta",
    workflowName: "Sincronizar inventario",
    endpoint: "/hooks/internal/inventory-sync",
    method: "PUT",
    status: "pending",
    statusCode: null,
    durationMs: 0,
    attempts: 1,
    receivedAt: minutesAgo(190),
    payload: { skus: 412, warehouse: "MAD-01" },
    errorMessage: null,
  },
];

export const MOCK_API_KEYS: readonly ApiKey[] = [
  {
    id: "key_1",
    name: "Producción - Webhook Principal",
    prefix: "fh_live",
    secret: "fh_live_9a8f7c6b5d4e3f2a10987654321fedcba",
    scope: "full",
    createdAt: "2026-03-01T10:00:00.000Z",
    lastUsedAt: "2026-09-20T15:30:00.000Z",
  },
  {
    id: "key_2",
    name: "Staging - Pruebas Locales",
    prefix: "fh_test",
    secret: "fh_test_1234567890abcdef1234567890abcdef",
    scope: "read",
    createdAt: "2026-05-15T08:20:00.000Z",
    lastUsedAt: "2026-09-18T11:05:00.000Z",
  },
];